name: yeastnet
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.1
  - pytorch=1.3.1
  - imageio
  - ipython
  - matplotlib
  - numpy
  - opencv
  - pip
  - pylint
  - python=3.6.9
  - scipy
  - tensorboard
  - torchvision
  - tqdm



