name: yeast-net-test
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.1=py36_0
  - astor=0.8.0=py36_0
  - astroid=2.2.5=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h7a1dbc1_0
  - cloudpickle=1.2.1=py_0
  - colorama=0.4.1=py36_0
  - cuda100=1.0=0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py36h009560c_0
  - cytoolz=0.10.0=py36hfa6e2cd_0
  - dask-core=2.2.0=py_0
  - decorator=4.4.0=py_0
  - freetype=2.9.1=ha9979f8_1
  - gast=0.2.2=py36_0
  - grpcio=1.16.1=py36h351948d_1
  - h5py=2.8.0=py36hf7173ca_2
  - hdf5=1.8.20=hac2f561_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - imageio=2.5.0=py36_0
  - intel-openmp=2019.4=245
  - ipython=7.7.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - isort=4.3.21=py36_0
  - jedi=0.13.3=py36_0
  - jpeg=9b=hb83a4c4_2
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py36ha925a31_0
  - lazy-object-proxy=1.4.1=py36he774522_0
  - libmklml=2019.0.5=0
  - libopencv=3.4.2=h20b85fd_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.8.0=h7bd577a_0
  - libtiff=4.0.10=hb898794_2
  - markdown=3.1.1=py36_0
  - matplotlib=3.1.0=py36hc8f65d3_0
  - matplotlib-base=3.1.1=py36h2852a4a_1
  - mccabe=0.6.1=py36_1
  - mkl=2019.4=245
  - mkl-service=2.0.2=py36he774522_0
  - mkl_fft=1.0.12=py36h14836fe_0
  - mkl_random=1.0.2=py36h343c172_0
  - mock=3.0.5=py36_0
  - networkx=2.3=py_0
  - ninja=1.9.0=py36h74a9793_0
  - numpy=1.16.4=py36h19fb1c0_0
  - numpy-base=1.16.4=py36hc3f5095_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h40b0b35_0
  - openssl=1.1.1c=he774522_1
  - parso=0.5.0=py_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.1.0=py36hdc69c19_0
  - pip=19.1.1=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - py-opencv=3.4.2=py36hc319ecb_0
  - pycparser=2.19=py36_0
  - pygments=2.4.2=py_0
  - pylint=2.3.1=py36_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py36h6538335_2
  - python=3.6.9=h5500b2f_0
  - python-dateutil=2.8.0=py36_0
  - pytorch=1.0.1=py3.6_cuda100_cudnn7_1
  - pytz=2019.1=py_0
  - pywavelets=1.0.3=py36h452e1ab_1
  - qt=5.9.7=vc14h73c81de_0
  - scikit-image=0.15.0=py36he350917_2
  - scipy=1.3.0=py36h29ff71c_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36h6538335_0
  - six=1.12.0=py36_0
  - sqlite=3.29.0=he774522_0
  - tensorboard=1.13.1=py36h33f27b4_0
  - tensorflow=1.13.1=mkl_py36hd212fbe_0
  - tensorflow-base=1.13.1=mkl_py36hcaf7020_0
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - torchvision=0.2.2=py_3
  - tornado=6.0.3=py36he774522_0
  - traitlets=4.3.2=py36h096827d_0
  - typed-ast=1.3.4=py36he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_4
  - wcwidth=0.1.7=py36h3d5aa90_0
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - wrapt=1.11.2=py36he774522_0
  - xz=5.2.4=h2fa13f4_4
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - protobuf==3.9.1
    - tensorboardx==1.8

